# Generated by Django 5.0 on 2023-12-13 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='information',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
